export const PAYMENT_ACTION_TYPES = {
  CHECK_PAYMENT_REQUEST: 'payment/CHECK_PAYMENT_REQUEST',
  PAYMENT_REQUEST_SUCCESS: 'payment/PAYMENT_REQUEST_SUCCESS',
  PAYMENT_REQUEST_FAILED: 'payment/PAYMENT_REQUEST_FAILED',
  CARD_PAYMENT_START: 'payment/CARD_PAYMENT_START',
  CARD_PAYMENT_SUCCESS: 'payment/CARD_PAYMENT_SUCCESS',
  CARD_PAYMENT_FAILED: 'payment/CARD_PAYMENT_FAILED',
};
