export const PAYMENT_ACTION_TYPES = {
  CHECK_PAYMENT_REQUEST: 'payment/CHECK_PAYMENT_REQUEST',
  PAYMENT_REQUEST_SUCCESS: 'payment/PAYMENT_REQUEST_SUCCESS',
  PAYMENT_REQUEST_FAILED: 'payment/PAYMENT_REQUEST_FAILED',
};
